### ISSUE TITLE
Specific score from map leaderboard endpoint

### ISSUE THREAD

**Issue by atsumiosu** [catcho2012/catcho_api#1]
It would be cool if there would be a optional parameter for the map leaderboard endpoint to get a specific user's scores.
For Example: `http://huutista.xyz/api/beatmaps/183357/leaderboard?u=49`
Returns: `{"score_id":902,"replay_hash":"7ea4981429d2f78dcea43057aa9c6552","submit_time":"2020-12-02T20:23:14.000Z","hit_geki":"233","hit_katu":"6","hit_miss":"0","hit_300":"1061","hit_100":"8","hit_50":"0","username":"Strafe","score":41076014,"perfect":0,"grade":"S","mods":"0","pass":1,"mode":0}`

**Comment by j1niux** [comment]
Thanks for the suggestion. You can now look up for specific score by username, for example: `http://huutista.xyz/api/beatmaps/183357/leaderboard?u=jiniux`. It returns a `score` object (that is `null` if there is no score submitted for that user).

It will be available in the next release.
